# CQ2: What distinguishes a plastic object from plastic debris?

# Description: This CQ requires identifying the characterizations provided for plastic objects and plastic debris by PlasticO and comparing them. 
# We decided to use the SPARQL query form DESCRIBE against the two dedicated classes to ensure full characterizations, including annotations and axiomatizations. 
# We opted for this approach as simply querying for definitions or direct superclasses may not be sufficient to distinguish the two classes, for instance with respect to specific properties characterizing plastic objects and debris. 
# Manual comparison of the query results can follow.

# # The SPARQL query runner used for the other queries does not work with the SPARQL form DESCRIBE. 
# Thus, we performed the queries against the local version of PlasticO, using the SPARQL Executor plug-in for Visual Studio Code, on Giorgio A. Ubbiali's laptop. 
# Results have been collected in a markdown file, findable in the same directory as this file.

# SPARQL query 2.1

PREFIX ClimOO: <https://www.w3id.org/climoo/climoo-plastico#>
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

DESCRIBE ClimOO:ClimOO_0000163

# SPARQL query 2.2

PREFIX ClimOO: <https://www.w3id.org/climoo/climoo-plastico#>
PREFIX owl: <http://www.w3.org/2002/07/owl#> 
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX obo: <http://purl.obolibrary.org/obo/>

DESCRIBE ClimOO:ClimOO_0000171




